version: '3.9'
services:
  hack_app:
    container_name: hack_app
    image: hack_app
    build: .
    ports:
      - "5001:5000"
    restart: unless-stopped
    environment:
      - PRODUCTION=false
      - DATABASE_URL=postgresql+psycopg2://root:root@hack_database/hack
      - INIT_TABLES=true
      - SECRET_KEY=!Y&a6Yov@I@B%AAZ2dThuKnDvloy&Q8
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=5
      - REFRESH_TOKEN_EXPIRE_HOURS=24

  hack_database:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: "hack"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - hack_database_volume:/var/lib/postgresql/data
    ports:
      - "5435:5432"




volumes:
  hack_database_volume:
